# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #==============#
  # NexusOS      #
  #==============#
  config.vm.define "nxos01" do |cfg|
    cfg.vm.box = "sysnet4admin/nxosv_v7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "NxOS01"
    end
  end

  #================#
  # Ansible Server #
  #================#

  config.vbguest.auto_update = false
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Server"
    end
    cfg.vm.hostname = "ansible-server"
    cfg.vm.network "private_network", ip: "192.168.8.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "centos_repo.sh", privileged: true
    cfg.vm.provision "shell", inline: "yum install epel-release -y"
    cfg.vm.provision "shell", inline: "yum install ansible -y"
    cfg.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end