---
# FTP 서버 설정
- name: Setup for FTP Server
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    # VSFTP 설치
    - name: Install vsftp
      yum:
        name: vsftpd
        state: present
    
    # VSFTP 환경설정
    - name: vsftp env for anonymous
      shell: "{{ item }}"
      with_items:
        - "sed -i -e 's/#anon_upload_enable=YES/anon_upload_enable=YES/g' /etc/vsftpd/vsftpd.conf"
        - "sed -i -e 's/#anon_mkdir_write_enable=YES/anon_mkdir_write_enable=YES/g' /etc/vsftpd/vsftpd.conf"

    # VSFTP 소유권 및 허가권 변경
    - name: chown & chmod
      shell: "{{ item }}"
      with_items:
        - "chown ftp.ftp /var/ftp/pub"
        - "chmod 777 /var/ftp/pub"

    # VSFTP 시작
    - name: start vsftpd service
      service:
        name: vsftpd
        state: started

# FTP 클라이언트
- name: Setup for FTP Client
  hosts: centos
  become: yes
  gather_facts: no

  tasks:
    # NCFTP 다운로드
    - name: download ncftp.rpm
      get_url:
        url: https://dl.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/n/ncftp-3.2.5-7.el7.x86_64.rpm
        dest: /home/vagrant/ncftp.rpm
    
    # NCFTP 설치
    - name: install ncftp.rpm
      yum:
        name: /home/vagrant/ncftp.rpm
        state: present