# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

#================#
# CentOS Nodes   #
#================#
  NODE_COUNT = 3
    NODE_COUNT.times do |i|
      config.vbguest.auto_update = false
      config.vm.define "ansible-node10#{i+1}" do |cfg|
        cfg.vm.box = "centos/7"
        cfg.vm.provider "virtualbox" do |vb|
          vb.name = "Ansible-Node10#{i+1}"
        end
        cfg.vm.host_name = "ansible-node10#{i+1}"
        cfg.vm.network "private_network", ip: "192.168.8.10#{i+1}"
        cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i+1}", auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "centos_repo.sh", privileged: true
        cfg.vm.provision "shell", path: "ssh_config.sh", privileged: true
      end
    end

#================#
# Ubuntu Nodes   #
#================#
  NODE_COUNT = 3
    NODE_COUNT.times do |i|
      config.vm.define "ansible-node20#{i+1}" do |cfg|
        cfg.vm.box = "ubuntu/trusty64"
        cfg.vm.provider "virtualbox" do |vb|
          vb.name = "Ansible-Node20#{i+1}"
        end
        cfg.vm.host_name = "ansible-node20#{i+1}"
        cfg.vm.network "private_network", ip: "192.168.8.20#{i+1}"
        cfg.vm.network "forwarded_port", guest: 22, host: "6020#{i+1}",
          auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      end
    end

#================#
# Ansible Server #
#================#
  config.vbguest.auto_update = false
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Server"
    end
    cfg.vm.host_name = "ansible-server"
    cfg.vm.network "private_network", ip: "192.168.8.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "centos_repo.sh", privileged: true
    cfg.vm.provision "shell", inline: "yum install -y epel-release"
    cfg.vm.provision "shell", inline: "yum install -y ansible"
    cfg.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
    cfg.vm.provision "file", source: "auto_pass.yml", destination: "auto_pass.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook auto_pass.yml", privileged: false
  end
end