---
- name: AWS remove
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: remove ec2
      ec2_instance:
        filters:
          "tag:Name": ansible-ec2-web
        state: absent

    - name: vpc infomation
      ec2_vpc_net_info:
        filters:
          "tag:Name": ansible-vpc
      register: vpc_info

    - name: remove security_group
      ec2_group:
        name: ansible-sg
        vpc_id: "{{vpc_info.vpcs[0].vpc_id}}"
        state: absent

    - name: remove route table
      ec2_vpc_route_table:
        vpc_id: "{{vpc_info.vpcs[0].vpc_id}}"
        tags:
          Name: ansible-pub-rt
        state: absent

    - name: remove subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.0.0.0/24
        tags:
          Name: ansible-sn
        state: absent

    - name: remove internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_info.vpcs[0].vpc_id}}"
        tags:
          Name: ansible-igw
        state: absent

    - name: remove vpc
      ec2_vpc_net:
        name: ansible-vpc
        cidr_block: 10.0.0.0/16
        tags:
          Name: ansible-vpc
        state: absent