---
- name: set hostname
  hosts: localhost
  gather_facts: no
  connection: loacl

  tasks:
    - name: set hostname
      ios_config:
        lines: hostname TEST
        provider:
          host: 192.168.10.11
          username: kim
          password: kim
          authorize: true
          auth_pass: cisco